### ISSUE TITLE
部署与功能请求

### ISSUE THREAD

**Issue by eryajf** [pddzl/kubefish#1]
目前readme没有介绍部署步骤，期待完善这块儿内容。我这边已经部署了起来，但是没有sql，没法往下进行了。

另外也可以基于action构建自动化的docker，便于大家部署体验，也能为项目带来更好的第一印象。

看了下配置，目前好像是只支持单集群，期待支持k8s集群配置化管理，从而在平台管理多集群。

**Comment by pddzl** [comment]
readme已添加集群外部署方式
